#!/usr/bin/env python3
"""Website Technical Report PDF Generator - Enterprise Edition"""
import sys, json, math
from datetime import datetime
from reportlab.lib.pagesizes import letter
from reportlab.lib.units import inch
from reportlab.lib.colors import HexColor
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_CENTER
from reportlab.platypus import (
    BaseDocTemplate, Frame, PageTemplate, Paragraph, Spacer,
    Table, TableStyle, PageBreak, Flowable, NextPageTemplate
)

C = {
    "bg": HexColor("#FFFFFF"), "surface": HexColor("#F9FAFB"),
    "surface_raised": HexColor("#F3F4F6"), "border": HexColor("#E5E7EB"),
    "text_primary": HexColor("#111827"), "text_secondary": HexColor("#6B7280"),
    "text_tertiary": HexColor("#9CA3AF"), "accent": HexColor("#2563EB"),
    "success": HexColor("#16A34A"), "warning": HexColor("#D97706"),
    "error": HexColor("#DC2626"), "info": HexColor("#2563EB"),
    "white": HexColor("#FFFFFF"),
}
SEV = {
    "Critical": (C["error"], HexColor("#FEF2F2")),
    "High": (C["warning"], HexColor("#FFFBEB")),
    "Medium": (C["info"], HexColor("#EFF6FF")),
    "Low": (C["text_secondary"], C["surface"]),
}

def sc_color(s):
    if s >= 80: return C["success"]
    elif s >= 60: return C["info"]
    elif s >= 40: return C["warning"]
    return C["error"]

def grade(s):
    if s >= 90: return "A+"
    elif s >= 80: return "A"
    elif s >= 70: return "B"
    elif s >= 60: return "C"
    elif s >= 50: return "D"
    return "F"

class AccentBar(Flowable):
    def __init__(self, width=470, height=3, color=None):
        Flowable.__init__(self)
        self.width = width; self.height = height; self.color = color or C["accent"]
    def draw(self):
        self.canv.setFillColor(self.color)
        self.canv.rect(0, 0, self.width, self.height, fill=1, stroke=0)

class ScoreGauge(Flowable):
    def __init__(self, score, size=160):
        Flowable.__init__(self)
        self.score = score; self.size = size
        self.width = size; self.height = size + 10
    def draw(self):
        c = self.canv; cx = self.size/2; cy = self.size/2+5; r = self.size/2-10
        color = sc_color(self.score)
        c.setStrokeColor(C["surface_raised"]); c.setLineWidth(14)
        c.arc(cx-r, cy-r, cx+r, cy+r, 0, 360)
        arc = 360 * self.score / 100
        c.setStrokeColor(color); c.setLineWidth(14)
        c.arc(cx-r, cy-r, cx+r, cy+r, 90, arc)
        c.setFillColor(C["white"]); c.circle(cx, cy, r-14, fill=1, stroke=0)
        c.setFillColor(C["text_primary"]); c.setFont("Helvetica-Bold", 40)
        c.drawCentredString(cx, cy+6, str(int(self.score)))
        c.setFillColor(C["text_tertiary"]); c.setFont("Helvetica", 11)
        c.drawCentredString(cx, cy-12, "out of 100")
        c.setFillColor(color); c.setFont("Helvetica-Bold", 13)
        c.drawCentredString(cx, cy-30, f"Grade {grade(self.score)}")

class ScoreBar(Flowable):
    def __init__(self, label, score, bar_max=260):
        Flowable.__init__(self)
        self.label = label; self.score = score; self.bar_max = bar_max
        self.width = 470; self.height = 26
    def draw(self):
        c = self.canv; bh = 10; lw = 170; bx = lw+10; by = (self.height-bh)/2
        fw = (self.score/100)*self.bar_max; color = sc_color(self.score)
        c.setFillColor(C["text_primary"]); c.setFont("Helvetica", 9)
        c.drawString(0, by+1, self.label)
        c.setFillColor(C["surface_raised"])
        c.roundRect(bx, by, self.bar_max, bh, 4, fill=1, stroke=0)
        if fw > 8:
            c.setFillColor(color)
            c.roundRect(bx, by, fw, bh, 4, fill=1, stroke=0)
        c.setFillColor(C["text_primary"]); c.setFont("Helvetica-Bold", 10)
        c.drawString(bx+self.bar_max+10, by+1, str(int(self.score)))

def hf(canvas, doc, data):
    canvas.saveState(); w, h = letter
    canvas.setStrokeColor(C["border"]); canvas.setLineWidth(0.5)
    canvas.line(50, h-40, w-50, h-40)
    canvas.setFillColor(C["text_tertiary"]); canvas.setFont("Helvetica", 7)
    canvas.drawString(50, h-36, "Website Technical Audit Report")
    b = data.get("brand_name", "")
    if b: canvas.drawRightString(w-50, h-36, b)
    canvas.line(50, 42, w-50, 42)
    canvas.drawString(50, 30, "Generated by Website Technical Audit Suite")
    canvas.drawRightString(w-50, 30, f"Page {doc.page}")
    canvas.restoreState()

def mkstyles():
    r = {}
    r["title"] = ParagraphStyle("T", fontName="Helvetica-Bold", fontSize=32, textColor=C["text_primary"], spaceAfter=4, leading=38)
    r["subtitle"] = ParagraphStyle("ST", fontName="Helvetica", fontSize=13, textColor=C["text_secondary"], spaceAfter=8, leading=18)
    r["h1"] = ParagraphStyle("H1", fontName="Helvetica-Bold", fontSize=20, textColor=C["text_primary"], spaceBefore=24, spaceAfter=12, leading=26)
    r["h2"] = ParagraphStyle("H2", fontName="Helvetica-Bold", fontSize=14, textColor=C["accent"], spaceBefore=16, spaceAfter=8, leading=18)
    r["body"] = ParagraphStyle("B", fontName="Helvetica", fontSize=9.5, textColor=C["text_primary"], spaceAfter=6, leading=14)
    r["bs"] = ParagraphStyle("BS", fontName="Helvetica", fontSize=8.5, textColor=C["text_secondary"], spaceAfter=4, leading=12)
    r["cap"] = ParagraphStyle("C", fontName="Helvetica", fontSize=7.5, textColor=C["text_tertiary"], spaceAfter=2, leading=10)
    r["lbl"] = ParagraphStyle("L", fontName="Helvetica-Bold", fontSize=8, textColor=C["text_secondary"], spaceBefore=4, spaceAfter=2, leading=10)
    r["ni"] = ParagraphStyle("NI", fontName="Helvetica", fontSize=9.5, textColor=C["text_primary"], spaceAfter=8, leading=14, leftIndent=18, firstLineIndent=-18)
    return r

def mcell(text, style, bold=False):
    fn = "Helvetica-Bold" if bold else "Helvetica"
    return Paragraph(text, ParagraphStyle("c", parent=style, fontName=fn, spaceAfter=0, spaceBefore=0))

def generate_report(data, output_path):
    st = mkstyles()
    doc = BaseDocTemplate(output_path, pagesize=letter, leftMargin=50, rightMargin=50, topMargin=56, bottomMargin=56)
    cw = letter[0] - 100
    cf = Frame(50, 56, cw, letter[1]-112, id="c", showBoundary=0)
    cvf = Frame(50, 56, cw, letter[1]-112, id="cv", showBoundary=0)
    doc.addPageTemplates([PageTemplate(id="cover", frames=[cvf]), PageTemplate(id="content", frames=[cf], onPage=lambda c,d: hf(c,d,data))])
    el = []
    overall = data.get("overall_score", 0)
    brand = data.get("brand_name", "")
    industry = data.get("industry", "")
    size = data.get("company_size", "")
    date_str = data.get("date", datetime.now().strftime("%B %d, %Y"))
    el.append(Spacer(1, 0.6*inch)); el.append(AccentBar(width=cw, height=3)); el.append(Spacer(1, 24))
    el.append(Paragraph("Website Technical", st["title"]))
    el.append(Paragraph("Audit Report", ParagraphStyle("t2", parent=st["title"], textColor=C["text_tertiary"], spaceAfter=16)))
    if brand: el.append(Paragraph(brand, ParagraphStyle("bn", fontName="Helvetica-Bold", fontSize=18, textColor=C["text_primary"], spaceAfter=4)))
    details = []
    if industry: details.append(industry)
    if size: details.append(f"~{size} employees")
    if details: el.append(Paragraph(" | ".join(details), st["subtitle"]))
    el.append(Paragraph(date_str, st["cap"])); el.append(Spacer(1, 28))
    el.append(ScoreGauge(overall, size=160)); el.append(Spacer(1, 20))
    summary = data.get("executive_summary", "")
    if summary: el.append(Paragraph(summary, ParagraphStyle("sum", fontName="Helvetica", fontSize=9, textColor=C["text_secondary"], leading=14, spaceAfter=12)))
    el.append(Spacer(1, 12)); el.append(AccentBar(width=cw, height=1, color=C["border"]))
    el.append(NextPageTemplate("content")); el.append(PageBreak())
    el.append(Paragraph("Score Breakdown", st["h1"])); el.append(Spacer(1, 8))
    cats = data.get("categories", {})
    for name in cats: el.append(ScoreBar(name, cats[name].get("score", 50)))
    el.append(Spacer(1, 16))
    td = [[mcell("Category",st["lbl"],True), mcell("Score",st["lbl"],True), mcell("Weight",st["lbl"],True), mcell("Status",st["lbl"],True)]]
    cn = list(cats.keys())
    for i, n in enumerate(cn):
        sc = cats[n].get("score", 50); w = cats[n].get("weight", "")
        stat = "Strong" if sc >= 75 else "Needs Work" if sc >= 50 else "At Risk"
        td.append([mcell(n,st["bs"]), mcell(f"{int(sc)}/100",st["bs"],True), mcell(w,st["bs"]), mcell(stat,st["bs"])])
    t = Table(td, colWidths=[200,70,60,80])
    ts = [("BACKGROUND",(0,0),(-1,0),C["surface"]),("LINEBELOW",(0,0),(-1,0),1,C["border"]),("LINEBELOW",(0,-1),(-1,-1),1,C["border"]),("TOPPADDING",(0,0),(-1,-1),6),("BOTTOMPADDING",(0,0),(-1,-1),6),("LEFTPADDING",(0,0),(-1,-1),8),("VALIGN",(0,0),(-1,-1),"MIDDLE")]
    for i in range(2, len(td), 2): ts.append(("BACKGROUND",(0,i),(-1,i),C["surface"]))
    for i in range(1, len(td)):
        sc = cats[cn[i-1]].get("score",50); ts.append(("TEXTCOLOR",(3,i),(3,i),sc_color(sc)))
    t.setStyle(TableStyle(ts)); el.append(t); el.append(PageBreak())
    el.append(Paragraph("Key Findings", st["h1"])); el.append(Spacer(1, 8))
    for f in data.get("findings", []):
        sev = f.get("severity","Medium"); txt = f.get("finding","")
        fg, bg = SEV.get(sev, (C["text_secondary"], C["surface"]))
        rd = [[Paragraph(f'<font color="{fg.hexval()}" size="7"><b>{sev.upper()}</b></font>', st["bs"]), Paragraph(txt, st["bs"])]]
        rt = Table(rd, colWidths=[65, cw-85])
        rt.setStyle(TableStyle([("BACKGROUND",(0,0),(0,0),bg),("BACKGROUND",(1,0),(1,0),C["white"]),("TOPPADDING",(0,0),(-1,-1),8),("BOTTOMPADDING",(0,0),(-1,-1),8),("LEFTPADDING",(0,0),(-1,-1),8),("RIGHTPADDING",(0,0),(-1,-1),8),("VALIGN",(0,0),(-1,-1),"TOP"),("LINEBELOW",(0,0),(-1,-1),0.5,C["border"]),("ALIGN",(0,0),(0,0),"CENTER")]))
        el.append(rt); el.append(Spacer(1, 2))
    el.append(PageBreak())
    el.append(Paragraph("Prioritised Action Plan", st["h1"])); el.append(Spacer(1, 8))
    el.append(AccentBar(width=cw, height=2, color=C["success"]))
    el.append(Paragraph("Quick Wins - This Week", st["h2"]))
    for i, item in enumerate(data.get("quick_wins",[]), 1): el.append(Paragraph(f"<b>{i}.</b>  {item}", st["ni"]))
    el.append(Spacer(1, 12)); el.append(AccentBar(width=cw, height=2, color=C["info"]))
    el.append(Paragraph("Medium-Term - This Month", st["h2"]))
    for i, item in enumerate(data.get("medium_term",[]), 1): el.append(Paragraph(f"<b>{i}.</b>  {item}", st["ni"]))
    el.append(Spacer(1, 12)); el.append(AccentBar(width=cw, height=2, color=C["accent"]))
    el.append(Paragraph("Strategic - This Quarter", st["h2"]))
    for i, item in enumerate(data.get("strategic",[]), 1): el.append(Paragraph(f"<b>{i}.</b>  {item}", st["ni"]))
    el.append(Spacer(1, 32)); el.append(AccentBar(width=cw, height=1, color=C["border"])); el.append(Spacer(1, 8))
    el.append(Paragraph("Confidential. Prepared for discussion purposes.", ParagraphStyle("disc", fontName="Helvetica", fontSize=7.5, textColor=C["text_tertiary"], alignment=TA_CENTER)))
    doc.build(el); return output_path

if len(sys.argv) < 2: print("Usage: python3 generate_pdf_report.py <data.json> [output.pdf]"); sys.exit(1)
with open(sys.argv[1]) as f: data = json.load(f)
out = sys.argv[2] if len(sys.argv) > 2 else "Website Technical-REPORT.pdf"
generate_report(data, out); print(f"Report generated: {out}")
